import os


SECRET_KEY = os.environ.get('SECRET_KEY')
DEBUG = True
SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL')
SQLALCHEMY_DATABASE_MODIFICATIONS = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
PROPAGATE_EXCEPTIONS = True
JWT_SECRET_KEY = os.environ.get("JWT_SECRET_KEY")
JWT_BLACKLIST_ENABLED = True
JWT_BLACKLIST_TOKEN_CHECKS = ["access", "refresh"]
UPLOADED_IMAGES_DEST = os.path.join("static", "images")
CELERY_RESULT_BACKEND=os.environ.get('CELERY_RESULT_BACKEND')
CELERY_BROKER_URL=os.environ.get('CELERY_BROKER_URL')
CELERY_TRACK_STARTED= True
CELERY_SEND_EVENTS= True
